### PR TITLE
Fix broken icon path

### PR DESCRIPTION
**Pull request by StriveForBest**
Fix path to clear icon; rename icons to have consistent names; correct image tag alt attribute

Currently the path to the "clear" icon is incorrect in one of the templates which results in broken image. The alt attribute was probably copy/pasted from the tag above it and hasn't been updated. Icon names were inconsistent. See screenshot.

screenshot 2018-04-05 09 46 58

### CODE REVIEW

**Comment by StriveForBest** [comment]
@bartTC i re-created a pull request to have one commit and some additional cleanup. Please merge as soon as possible if it looks good to you. Currently we have the "Clear" icon broken for a couple of production websites whoops.

**Comment by StriveForBest** [comment]
CI looks good, it's just an error trying to download a python version that's not available. For everything else, no errors: https://travis-ci.org/lincolnloop/django-dynamic-raw-id/builds/362636179?utm_source=github_status&utm_medium=notification

**Comment by bartTC** [comment]
This is looking all fine, thanks! Surprised I didn't see that, I ran all django variants in tox and never saw missing icons.

**Comment by bartTC** [comment]
I released v2.4 with this and your earlier admin JS fix. Thanks!

https://pypi.org/project/django-dynamic-raw-id/2.4/

**Comment by StriveForBest** [comment]
@bartTC glad I was some help :) Thanks for taking in my changes

**Comment by StriveForBest** [comment]
and oh man, thanks for renaming it! we know it's raw, but salmonella hahaha. How about `django-tartar[-field]` or `django-sashimi[-field]`?

**Pull request merged**
